export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const GEOLOCATION_REQUEST = 'GEOLOCATION_REQUEST'
export const GEOLOCATION_SUCCESS = 'GEOLOCATION_SUCCESS'
export const GEOLOCATION_ERROR = 'GEOLOCATION_ERROR'
export const GEOLOCATION_TICK = 'GEOLOCATION_TICK'

export const GEOLOCATION_MARKER_REQUEST = 'GEOLOCATION_MARKER_REQUEST'
export const GEOLOCATION_MARKER_SUCCESS = 'GEOLOCATION_MARKER_SUCCESS'
export const GEOLOCATION_MARKER_ERROR = 'GEOLOCATION_MARKER_ERROR'

export const FLIGHT_INFO_SUCCESS = 'FLIGHT_INFO_SUCCESS'
export const FLIGHT_INFO_ERROR = 'FLIGHT_INFO_ERROR'
