export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const GEOLOCATION_REQUEST = 'GEOLOCATION_REQUEST'
export const GEOLOCATION_SUCCESS = 'GEOLOCATION_SUCCESS'
export const GEOLOCATION_ERROR = 'GEOLOCATION_ERROR'
